import { ICalculatorButton } from './calcalator.interface';

export const CALCULATOR_BUTTONS: ICalculatorButton[] = [
  {
    label: 'AC',
    type: 'function',
    action: 'reset',
    // keyCode: 27,
    enabled: true,
  },
  {
    label: '-/+',
    type: 'function',
    action: 'chaneSign',
    // keyCode: 0,
    enabled: false,
  },
  {
    label: '%',
    type: 'function',
    action: 'percent',
    // keyCode: 0,
    enabled: false,
  },
  {
    label: '/',
    type: 'function',
    action: 'divide',
    // keyCode: 111,
    enabled: true,
  },
  {
    label: '7',
    value: 7,
    type: 'number',
    // keyCode: 103,
    enabled: true,
  },
  {
    label: '8',
    value: 8,
    type: 'number',
    // keyCode: 104,
    enabled: true,
  },
  {
    label: '9',
    value: 9,
    type: 'number',
    // keyCode: 105,
    enabled: true,
  },
  {
    label: '*',
    type: 'function',
    action: 'multiply',
    // keyCode: 106,
    enabled: true,
  },
  {
    label: '4',
    value: 4,
    type: 'number',
    // keyCode: 100,
    enabled: true,
  },
  {
    label: '5',
    value: 5,
    type: 'number',
    // keyCode: 101,
    enabled: true,
  },
  {
    label: '6',
    value: 6,
    type: 'number',
    // keyCode: 102,
    enabled: true,
  },
  {
    label: '-',
    value: 0,
    type: 'function',
    action: 'subtract',
    // keyCode: 109,
    enabled: true,
  },
  {
    label: '1',
    value: 1,
    type: 'number',
    // keyCode: 97,
    enabled: true,
  },
  {
    label: '2',
    value: 2,
    type: 'number',
    // keyCode: 98,
    enabled: true,
  },
  {
    label: '3',
    value: 3,
    type: 'number',
    // keyCode: 99,
    enabled: true,
  },
  {
    label: '+',
    value: 0,
    type: 'function',
    action: 'add',
    // keyCode: 107,
    enabled: true,
  },
  {
    label: '0',
    value: 0,
    type: 'number',
    // keyCode: 98,
    enabled: true,
  },
  {
    label: '.',
    type: 'number',
    action: 'point',
    // keyCode: 110,
    enabled: false,
  },
  {
    label: '.',
    type: 'number',
    action: 'point',
    // keyCode: 110,
    enabled: false,
  },
  {
    label: '=',
    type: 'function',
    action: 'equal',
    // keyCode: 13,
    enabled: true,
  },
];
